# Generated by Django 5.0.4 on 2024-06-17 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='comuna',
            new_name='comuna_cliente',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='direccion',
            new_name='direccion_cliente',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='email',
            new_name='email_cliente',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='giro_comercial',
            new_name='giro_comercial_cliente',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nombre_razon_social',
            new_name='nombre_razon_social_cliente',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='rut',
            new_name='rut_cliente',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='telefono',
            new_name='telefono_cliente',
        ),
    ]
